# -*- coding: utf-8 -*-
"""main.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qKzX9r-KnNtUSZIYHF50Jumy1WJyCj92
"""

from fastapi import FastAPI
from fastapi.middleware.cors import CORSMiddleware
import pandas as pd

app = FastAPI()

app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_methods=["*"],
    allow_headers=["*"],
)

@app.get("/data")
def get_data():
    df = pd.read_excel("responses.xlsx")

    people = []
    for _, row in df.iterrows():
        people.append({
            "name": row["Your Name (for message attribution)"],
            "entries": [
            ["The One Word Essence", row["Apa satu kata yang paling sempurna menggambarkan Kinan dan apa alasannya? "]],
            ["The Shared History", row["Apa kenangan favorit atau momen paling berkesan yang pernah kamu lalui bersama Kinan?"]],
            ["The Superpower", row["Apa satu hal yang Kinan lakukan lebih baik daripada orang lain? (Bisa berupa bakat, sifat, atau caranya memperlakukan orang lain.)"]],
            ["The Heart to Heart", row["Jika kamu bisa menyampaikan satu hal tentang dampak positif yang dia berikan di hidupmu atau alasan mengapa kamu bersyukur berteman dengannya, apa yang ingin kamu katakan? "]],
            ["Birthday Wishes", row["Send a birthday wish , message, prayers or supports to Kinan."]],
            ]
        })

    return people